// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxopcsctgepswgzukdjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4b3Bjc2N0Z2Vwc3dnenVrZGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTE2OTYsImV4cCI6MjA2NzA2NzY5Nn0.gAoKbJtM0O58uGsybvRYYLfjF7BkKOFvMXyUtbMOI7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});